// Code generated by MockGen. DO NOT EDIT.
// Source: currency.go

// Package mock_v1 is a generated GoMock package.
package mock_v1

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCurrencyConverter is a mock of CurrencyConverter interface.
type MockCurrencyConverter struct {
	ctrl     *gomock.Controller
	recorder *MockCurrencyConverterMockRecorder
}

// MockCurrencyConverterMockRecorder is the mock recorder for MockCurrencyConverter.
type MockCurrencyConverterMockRecorder struct {
	mock *MockCurrencyConverter
}

// NewMockCurrencyConverter creates a new mock instance.
func NewMockCurrencyConverter(ctrl *gomock.Controller) *MockCurrencyConverter {
	mock := &MockCurrencyConverter{ctrl: ctrl}
	mock.recorder = &MockCurrencyConverterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrencyConverter) EXPECT() *MockCurrencyConverterMockRecorder {
	return m.recorder
}

// Convert mocks base method.
func (m *MockCurrencyConverter) Convert(amount float64, fromCurrency, toCurrency string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Convert", amount, fromCurrency, toCurrency)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Convert indicates an expected call of Convert.
func (mr *MockCurrencyConverterMockRecorder) Convert(amount, fromCurrency, toCurrency interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Convert", reflect.TypeOf((*MockCurrencyConverter)(nil).Convert), amount, fromCurrency, toCurrency)
}
