port: "8080"

db:
  username: kapitonov
  host: "localhost"
  port: "5432"
  password: root
  dbname: "postgres"
  sslmode: "disable"

log:
  is_local: true
  level: "debug"
  add_source: true
  is_json: false
  set_default: true
